import { MoreHorizontal } from 'lucide-react'
import { PageHeader } from '../../components/ui/PageHeader'
import { Panel } from '../../components/ui/Panel'
import { StatusBadge } from '../../components/ui/StatusBadge'
import { TableToolbar } from '../../components/ui/TableToolbar'

export function Template02Page() {
  return <div className="w-full"><PageHeader eyebrow="Table template" title="Template 02" description="Gunakan layout ini untuk daftar data dengan search, filter, tabs, dan pagination." actionLabel="Add item"/><Panel><div className="flex gap-2 overflow-x-auto border-b border-slate-200/80 px-4 text-[13px] dark:border-white/10">{['All 128','Active 84','Pending 32','Archived 12'].map((tab,index)=><button key={tab} className={`my-2 whitespace-nowrap rounded-xl px-3 py-2 ${index===0?'bg-brand-50 font-medium text-brand-700 dark:bg-brand-500/10 dark:text-brand-100':'text-slate-500 hover:bg-slate-100/70 dark:hover:bg-white/5'}`}>{tab}</button>)}</div><TableToolbar placeholder="Search data..."/><div className="overflow-x-auto"><table className="w-full text-left text-[13px]"><thead className="bg-slate-50/60 text-[11px] uppercase tracking-wide text-slate-500 dark:bg-white/[0.025]"><tr>{['Name','Type','Owner','Updated','Value','Status',''].map((head)=><th key={head} className="px-5 py-3 font-medium">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-200/60 dark:divide-white/5">{Array.from({length:7},(_,index)=><tr key={index} className="hover:bg-slate-50/60 dark:hover:bg-white/[0.02]"><td className="px-5 py-4 font-medium text-brand-600">Example item {String(index+1).padStart(2,'0')}</td><td className="px-5 py-4">Type name</td><td className="px-5 py-4">User name</td><td className="px-5 py-4 text-slate-500">21 Sep 2026</td><td className="px-5 py-4 font-medium">{(index+1)*240}</td><td className="px-5 py-4"><StatusBadge tone={index%3===0?'amber':'green'}>{index%3===0?'Pending':'Active'}</StatusBadge></td><td className="px-5"><MoreHorizontal size={18} className="text-slate-400"/></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-200/80 px-5 py-4 text-[13px] dark:border-white/10"><p className="text-slate-500">Showing 1–7 of 128</p><div className="flex gap-2"><button className="rounded-xl border border-slate-200/80 px-3 py-1.5 text-slate-500 dark:border-white/10">Previous</button><button className="rounded-xl border border-slate-200/80 px-3 py-1.5 dark:border-white/10">Next</button></div></div></Panel></div>
}
