import { Save } from 'lucide-react'
import { PageHeader } from '../../components/ui/PageHeader'
import { Panel } from '../../components/ui/Panel'

const inputClass = 'mt-2 h-10 w-full rounded-xl border border-slate-200/80 bg-white/60 px-3 text-[13px] outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/15 dark:border-white/10 dark:bg-white/[0.035]'

export function Template04Page() {
  return <div className="w-full"><PageHeader eyebrow="Form template" title="Template 04" description="Gunakan layout ini untuk create, edit, settings, atau konfigurasi data."/><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><Panel><div className="border-b border-slate-200/80 p-5 dark:border-white/10"><h2 className="font-semibold">Section title</h2><p className="mt-1 text-xs text-slate-500">Explain what the user should enter in this section.</p></div><form className="grid gap-5 p-5 sm:grid-cols-2"><label className="text-[13px] font-medium">Text field<input className={inputClass} placeholder="Enter a value"/></label><label className="text-[13px] font-medium">Select field<select className={inputClass}><option>Select an option</option><option>Option one</option><option>Option two</option></select></label><label className="text-[13px] font-medium sm:col-span-2">Long text<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200/80 bg-white/60 p-3 text-[13px] outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-500/15 dark:border-white/10 dark:bg-white/[0.035]" placeholder="Enter a longer description"/></label><label className="text-[13px] font-medium">Date field<input type="date" className={inputClass}/></label><label className="text-[13px] font-medium">Number field<input type="number" className={inputClass} placeholder="0"/></label><label className="flex items-start gap-3 sm:col-span-2"><input type="checkbox" className="mt-1 size-4 accent-brand-600"/><span><span className="block text-[13px] font-medium">Checkbox label</span><span className="text-xs text-slate-500">Add a short explanation for this option.</span></span></label></form><div className="flex justify-end gap-3 border-t border-slate-200/80 p-5 dark:border-white/10"><button type="button" className="h-10 rounded-xl border border-slate-200/80 px-4 text-[13px] dark:border-white/10">Cancel</button><button type="button" className="flex h-10 items-center gap-2 rounded-xl bg-brand-600 px-4 text-[13px] font-medium text-white"><Save size={16}/>Save changes</button></div></Panel><Panel className="h-fit"><div className="border-b border-slate-200/80 p-5 dark:border-white/10"><h2 className="font-semibold">Helper panel</h2></div><div className="space-y-4 p-5 text-[13px] leading-5 text-slate-500"><p>Use this area for guidance, a preview, metadata, or secondary controls.</p><div className="rounded-xl bg-brand-50 p-4 text-brand-700 dark:bg-brand-500/10 dark:text-brand-100">Helpful information can be highlighted here.</div></div></Panel></div></div>
}
